/*
 * Copyright 2026 Flant JSC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * 	http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package clusterprovider

import (
	"context"

	"k8s.io/apimachinery/pkg/api/resource"
)

// DiskSpec describes a block device to attach to a cluster node.
type DiskSpec struct {
	// NodeName is the cluster node the disk must become visible on. Required.
	NodeName string
	// Name identifies the disk; auto-generated by the provider when empty.
	Name string
	// StorageClass selects the backing storage class; provider default when empty.
	StorageClass string
	// Size is the requested disk size. Required.
	Size resource.Quantity
}

// DiskRef identifies an attached disk for detach operations.
type DiskRef struct {
	Name     string
	NodeName string
}

// Disk describes a block device managed by a DiskManager.
type Disk struct {
	Name         string
	NodeName     string
	StorageClass string
	Size         resource.Quantity
}

// DiskManager attaches and detaches extra block devices on cluster nodes.
// Implementations differ per provider (DVP: VirtualDisk +
// VirtualMachineBlockDeviceAttachment on the base cluster; Commander: cluster
// values update + reconcile), but share one post-contract:
//
//   - Attach blocks until the block device is visible on the target node (the
//     wait budget is the provider's, bounded by ctx).
//   - Detach is idempotent: detaching an absent disk returns nil.
type DiskManager interface {
	Attach(ctx context.Context, spec DiskSpec) (*Disk, error)
	Detach(ctx context.Context, ref DiskRef) error
	List(ctx context.Context, nodeName string) ([]Disk, error)
}
