name: Go checks for images

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  go_linter:
    name: Go linter for images
    runs-on: [self-hosted, regular]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Go lint
        uses: deckhouse/modules-actions/go_linter@v12
        with:
          go_version: "1.25.9"

  go_tests:
    name: Go tests for images
    runs-on: [self-hosted, regular]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Go tests
        uses: deckhouse/modules-actions/go_tests@v12
        with:
          go_version: "1.25.9"

